### ISSUE TITLE
Could you release the code for getting the ground points?

### ISSUE THREAD

**Issue by sunnyHelen** [yinjunbo/ProposalContrast#11]
Hi, Junbo. Thanks a lot for sharing your great work. Could you please release the code for getting the ground points? I want to use it on other datasets, e.g., Nuscenes. Or could you give more detail about it?

**Comment by yinjunbo** [comment]
Hi, our code follows the example at [pyransac3d](https://pypi.org/project/pyransac3d/). We empirically set the hyper-parameter (i.e., distance above the plane) as 0.1. You can also try other values.
