### ISSUE TITLE
baseline results

### ISSUE THREAD

**Issue by zwei-lin** [yinjunbo/ProposalContrast#2]
Hi,
  Thanks for the great work!
  I have one question about the baseline results of Table 2 in the paper. The paper claims that the baseline results on Waymo Dataset are obtained following OpenPCDet. However, I find the results reported in the paper are much lower than that in OpenPCDet. For example, the result of CenterPoint (VoxelNet) is 61.81/61.30, 63.62/57.79, and 64.96/63.77 in the paper. OpenPCDet reports the result of 63.16/62.65, 64.27/58.23, and 66.11/64.87 for CenterPoint (VoxelNet).

**Comment by mu-cai** [comment]
I have the same question, seems like the improvement upon the "true" baseline is much smaller if compared to the openpcdet repo.

**Comment by yinjunbo** [comment]
Thanks for your interest. The CenterPoint results in Tab.2 are directly borrowed from GCC-3D(ICCV-21). Other results are based on OpenPCDet-v0.3 that only contained Waymo models of SECOND, PartA2 and PV-RCNN at that time. We implement CenterPoint based on the official codebase, thus the results are different from OpenPCDet-v0.5 as you indicated. We would like to add support for OpenPCDet-v0.5 to further improve the results.

**Comment by Runjian-Chen** [comment]
Hello, thank you for your interesting work!

I notice that the "training from scratch" results are also borrowed from GCC-3D (ICCV 2021). However, you mentioned that you use a different implementation of CenterPoint. Thus the "training from scratch" results should be conducted with your implementation.

Would you offer your implementation of CenterPoint in the future?

**Comment by yinjunbo** [comment]
The ‘different implementation of CenterPoint’ refers the model for ONCE dataset. We don't have plan to release the ONCE version right now. Thanks for you attention!

**Comment by Runjian-Chen** [comment]
Thank you for your reply! But would you provide training from scratch results on Waymo with your implementation? Because to demonstrate the effectiveness of pre-training methods, we need the same model for training from scratch and for initialized by pre-training methods.

**Comment by yinjunbo** [comment]
You can just find the Waymo results in the 'Main Results' part of Readme. Thanks.

**Comment by Runjian-Chen** [comment]
Thanks for your prompt reply! In my understanding, the results are mAPH for different categories and overall. The results are different from what you present in the paper. Is that right? Thank you again for your patience.

**Comment by yinjunbo** [comment]
mAPH is right the 'overall' metirc mentioned in the paper. The baseline results in thie repo are also from our implementation, thus are different from the GCC-3D baseline results in the paper.

**Comment by Runjian-Chen** [comment]
Got it. Thank you for the clarification!
