### ISSUE TITLE
How did you sample the datasets for data-efficient 3d detection

### ISSUE THREAD

**Issue by Hiusam** [yinjunbo/ProposalContrast#5]
Hi, thank you for your excellent work.

In your paper about data-efficient 3D object detection on the Waymo dataset, you said "During fine-tuning, various fractions of training data are uniformly sampled". I want to ask whether you sample the data frame by frame or scene by scene.
Frame by Frame means all scenes(399 scenes in your paper) are included but every (for example for 10%) 10 frames you sample 1.
Scene by scene means you sample some scenes(40 scenes for 10%) and all the frames in those scenes are used for fine-tuning.

Also, how do you split the training samples of KITTI into three groups?

Thank you for your answer.

**Comment by yinjunbo** [comment]
1. We use the 'frame by frame' paradigm in Waymo.
2. For each KITTI sub-set (20% or 50%), we downsample the whole training set 3 times at random, and report the average performance. (Btw, you can also refer to the downsample rules in [3DIoUMatch](https://github.com/THU17cyz/3DIoUMatch)).

**Comment by Hiusam** [comment]
Thank you.
