### ISSUE TITLE
Is it necessary to remove road points when pre-training?

### ISSUE THREAD

**Issue by Hiusam** [yinjunbo/ProposalContrast#7]
Hi, thank you for your excellent work. 
I am trying to reimplement your code and my codebase does not support removing points. I am wondering if it is necessary to remove the road points when pre-training. Will not removing hurt the performance? 
Thank you.

**Comment by yinjunbo** [comment]
Hi, thanks for your attention.

Does the 'removing points' refers to the ground points?
If so, actually, we donot remove the ground points, but we just record the
indices of the ground points, so as to reduce the sampling on the massive
ground.
This process assures the class balance of proposals, and improves the
performance by ~0.5mAP.
Hope this helps.

Best,
Junbo

Hiusam ***@***.***> 于2022年10月19日周三 20:37写道：

**Comment by Hiusam** [comment]
Thank you very much.
