### ISSUE TITLE
How do you re-implement PointContrast and DepthContrast?

### ISSUE THREAD

**Issue by Hiusam** [yinjunbo/ProposalContrast#8]
Hi, thank you for your excellent work.

I wonder how you re-implement PointContrast and DephtContrast in your codebase? Can you give me some hints? 

If you can provide the code (or some code snippets), I will appreciate it very much.

**Comment by yinjunbo** [comment]
Hi, thanks for you interest.
We implemented PointContrast by randomly sampling points from two augmented views and then enforcing point-wise contrastive loss. This can be easily realized by our codebase.
As for DephtContrast, we directly followed their offcial code `https://github.com/facebookresearch/DepthContrast`.
